spring:
  profiles:
    active: dev
  redis: 
    url: ${REDIS_URL}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

summarization:
  api:
    url: ${SUMMARIZATION_API}
    token: ${HF_TOKEN}


weather:
  api:
    key: ${WEATHER_API_KEY}

logging:
  level:
    com:
      example:
        springJournal: ERROR
scheduler:
  weekly-cron: 0 0 9 * * MON    # every Monday at 9 AM
  monthly-cron: 0 0 9 1 * *     # first day of month at 9 AM